server:
  http_listen_port: 9080
clients:
  - url: http://localhost:3100/loki/api/v1/push
scrape_configs:
  - job_name: "java_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "java"
          __path__: /var/log/java_app/*.log  # Remplacez par le chemin des logs
